// <auto-generated />
namespace MvcApplication1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class change_foreign_key_add_int_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_foreign_key_add_int_id));
        
        string IMigrationMetadata.Id
        {
            get { return "201911081529059_change_foreign_key_add_int_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
